config/routes.rb
Rails.application.routes.draw do

  root to: 'welcomes#index'
  resources :welcomes
  resources :users, only: [:new]

  post '/users', to: 'users#create'
 
  resources :authentication, only: [:index]
  resources :ratings, only: [:new, :create]

  get 'products/check_role', to: 'products#check_role', as: 'check_role'
  post '/auth/login', to: 'authentication#login'
  get 'users/new_import_file', to: 'users#new_import_file', as: 'new_import_file'
  post 'users/update_password', to: 'users#update_password', as: 'update_password'
  post 'users/import_users', to: 'users#import_users', as: 'import_users'
  post 'orders/search', to: 'orders#search', as: 'search'
  post 'products/import_users', to: 'products#import_users'
  get 'products/new_import_file', to: 'products#new_import_file'

  resources :products, only: [:new, :index, :show, :create] do
    collection do
      get 'search'
    end
  end
  resources :orders, only: [:new, :create]

  if Rails.env.development?
    mount LetterOpenerWeb::Engine, at: "/letter_opener"
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  belongs_to :imageable, polymorphic: true
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user, dependent: :destroy
  has_many :images, as: :imageable
  belongs_to :order, dependent: :destroy
  has_many :ratings, dependent: :destroy
end

app/models/rating.rb
class Rating < ApplicationRecord
  belongs_to :product
  belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/token.rb
class Token < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  rolify

  require "securerandom"
  
  has_secure_password
  # has_and_belongs_to_many :role, :join_table => :users_roles
  has_many :products, dependent: :destroy
  validates :email, format: URI::MailTo::EMAIL_REGEXP
  has_many :images, as: :imageable
  has_one :token
 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include JsonWebToken

  before_action :authenticate_request ,except: [:index, :login]

  private

  def authenticate_request 	
    header = request.headers["Authorization"]
    header = header.split(" ").last if header 
    decoded = jwt_decode(header)
    @current_user = User.find(decoded[:user_id]) 	
  end 
  
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
  before_action :authenticate_request , except: [:login, :index]
  
  def index
  end

  def login
    @user = User.find_by_email(params[:email])
    if @user&.authenticate(params[:password])
      user_roles = @user.roles.pluck(:name)
      @token = jwt_encode(user_id: @user.id, roles: user_roles)
      redirect_to products_path(token: @token)
      # redirect_to check_role_path(current_user: @current_user)
    else
      render json: { error: 'unauthorized' }, status: :unauthorized
    end
  end

end

app/controllers/concerns/json_web_token.rb
require "jwt" 

module JsonWebToken 

  extend ActiveSupport::Concern 
  
  SECRET_KEY = Rails.application.secret_key_base

  def jwt_encode(payload, exp = 7.days.from_now) 
    payload[:exp] = exp.to_i 
    JWT.encode(payload, SECRET_KEY) 
  end 	

  def jwt_decode(token)
    decoded = JWT.decode(token, SECRET_KEY)[0] 
    HashWithIndifferentAccess.new decoded
  end 
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :authenticate_request ,except: [:create, :new]
  
  def new
    @order = Order.new
  end

  def create
    @order = Order.new(order_params) 
    if @order.save
      redirect_to new_product_path
    else 
      render 'new'
    end
  end

  def search
    @search_product = params[:search_product]
    @search_user = params[:search_user]

    order_data = Product.find_by(products_name: "#{@search_product}") || Product.find_by(user_id:  "#{@search_user}")

    if order_data
      order = Order.find_by(id: order_data.order_id)
      render json: order
    else
      render json: { errors: "Enter valid information"}
    end
  end

  private

  def order_params
    params.require(:order).permit(:order_detail)
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_request, except: [:index, :create, :new, :show, :new_import_file, :import_users, :search]
  before_action :check_role 

  def index
    @products = Product.paginate(page: params[:page], per_page: 10)
    # @products = Product.all
  end

  def new
    @product = Product.new
  end
  
  def create
    @product = Product.new(product_params) 
    if @product.save
      render 'create'
    else 
      render json: { errors: @product.errors.full_messages },
      status: :unprocessable_entity
    end
  end

  def show
    @product = Product.find(params[:id])
  end 
  
  def new_import_file
  end

  def import_users
    uploaded_file = params[:file]
    ProductWorker.perform_async(uploaded_file.path)
    render json: { message: "CSV is successfully import" }
  end

  def search
    product_name = params[:product][:product_id]
    @results = Product.where("products_name LIKE ?", "%#{product_name}%")
  
    render 'search'
  end
  

  private

  def product_params
    params.require(:product).permit(:user_id, :products_name, :price, :order_id)
  end

  def check_role
    token = params[:token]
    if token
      payload = jwt_decode(token)
      @current_user_roles = payload['roles']

      if @current_user_roles.include?('admin')
        render 'create'
      else
        redirect_to products_path
      end
    else

    end
  end

end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  before_action :authenticate_request, except: [:create, :new]

  def index
    @rating = @product.rating.all
  end
  
  def new 
    @rating = Rating.new
  end

  def create
    @product = Product.find_by(params[:id])
    @rating = @product.ratings.new(rating_params)
    current_user = @rating.user  

    if @rating.save
      render 'create'
    else
      render json: { errors: @rating.errors.full_messages },
      status: :unprocessable_entity
    end
  end

  private

  def rating_params
    params.require(:rating).permit(:product_id, :rating_value, :comment, :user_id)
  end
end

app/controllers/users_controller.rb
require 'csv'

class UsersController < ApplicationController
  before_action :authenticate_request, except: [:create, :new, :new_import_file, :import_users]
  
  def index
    @users = User.all
    render json: @users, status: :ok
  end
  
  def new
    @user = User.new
  end

  def show 
    render json: @user, status: :ok
  end

  def create
    @user = User.new(user_params)
    if @user.save
      render 'create'
    else 
      render json: { errors: @user.errors.full_messages },
      status: :unprocessable_entity
    end
  end

  def new_import_file
  end

  def import_users
    uploaded_file = params[:file]
    UserWorker.perform_async(uploaded_file.path)
    render json: { message: "CSV is successfully import" }
  end

  def update_password
    @user = User.find_by(email: params[:email])

    if @user.authenticate(params[:current_password])
      if @user.update(password: params[:new_password])
        UserMailer.with(user: @user).welcome_email.deliver_now
        render json: { message: "Password updated successfully" }
      else
        render json: { errors: @user.errors.full_messages }, status: :unprocessable_entity
      end
    else
      render json: { error: "Current password is incorrect" }, status: :unprocessable_entity
    end
  end

  def update
    unless @user.update(user_params)
      render json: { errors: @user.errors.full_messages },
      status: :unprocessable_entity
    end
  end

  def destroy
    @user.destroy
  end

  private

  def user_params
    params.require(:user).permit(:username, :email, :password)
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController
  
  def index
  end

end

app/views/authentication/index.html.erb
<h1>Please enter email and password</h1>

<%= form_with model: @user, url: auth_login_path, method: :post do |form| %>

  <div class="field" style="margin-bottom: 5px;">
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>

  <div class="field" style="margin-bottom: 5px;">
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </div>

  <div>
    <%= form.submit "login" %>
  </div>
  
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css">
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.min.js"></script>
</head>
<body>
  <div class="container-fluid bg-primary">
    <div class="row">
      <div class="col-md-6 offset-md-3 text-center py-5">
        <%= yield %>
      </div>
    </div>
  </div>
</body>
</html>

app/views/orders/new.html.erb
<%= form_for @order do |f| %>
  
  <div class="field" style="margin-bottom: 10px;">
    <%= f.label :order_detail %>
    <%= f.text_field :order_detail %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/products/create.html.erb
<%= hidden_field_tag :token, value: @token %>
  <table class = "table"; border= 2px;>
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <% if @product.present? %>
        <tr>
          <td><%= @product.products_name %></td>
          <td><%= @product.price %></td>
        </tr>
      <% else %>
        <tr>
          <td colspan="2">No products found.</td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= link_to 'Create product', new_product_path, class: "btn btn-primary" %>

app/views/products/index.html.erb
<h3>Product List<%= link_to '     Import File', products_new_import_file_path , class: "btn btn-primary" %> 
  <h6><%= form_with model: Product.new, url: search_products_path, method: :get do |f| %>
    <%= f.label :product_id, 'Select a Product:' %>
    <%= f.collection_select(:product_id, Product.all, :products_name, :products_name, include_blank: 'Select a Product') %>
    <%= f.submit 'Search' %>
  <% end %></h6>
</h3>
<%= hidden_field_tag :token, value: @token %>

  <table class = "table"; border= 2px;>
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @products.each do |p| %>
        <tr>
          <td><%= p.products_name %></td>
          <td><%= p.price %></td>
          <td>
            <%= link_to 'View Detail', product_path(p.id), class: "btn btn-primary" %>  
            <% if @current_user_roles&.include?('admin') %>
              <%= link_to 'Create Product', new_product_path, class: "btn btn-primary" %>
            <% else %>
              <%= link_to 'Add Rating', new_rating_path, class: "btn btn-primary" %>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>

<div class="pagination">
  <%= will_paginate @products %>
</div>

app/views/products/new.html.erb
<%= hidden_field_tag :token, value: @token %>

<%= form_for @product do |f| %>

  <div class="field" style="margin-bottom: 8px;">
    <%= f.label :products_name %>
    <%= f.text_field :products_name %>
  </div>

  <div class="field" style="margin-bottom: 8px;">
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>

  <div class="field" style="margin-bottom: 8px;">
    <%= f.label :user_id %>
    <%= f.collection_select(:user_id, User.all, :id, :username, include_blank: 'Select a User') %>
  </div>

  <div class="field" style="margin-bottom: 8px;">
    <%= f.label :order_id %>
    <%= f.collection_select(:order_id, Order.all, :id, :order_detail, include_blank: 'Select an Order') %>
    <%= link_to 'Add Order', new_order_path, class: 'btn btn-primary', remote: true %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/products/new_import_file.html.erb
<%= form_with(url: '/products/import_users', method: 'post', local: false, multipart: true) do |form| %>
  <div class="form-group">
    <%= form.label 'file', 'Select a CSV file:' %>
    <%= form.file_field 'file' %>
  </div>
  
  <%= form.submit 'Import File', class: 'btn btn-primary' %>
<% end %>

app/views/products/search.html.erb
<div>
  <h2>Here is the results for "<%= params[:product][:product_id] %>":</h2>
  <center><% if @results.any? %>
    <table class="table"; border= 2px >
      <thead>
        <tr>
          <th>Product Name</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @results.each do |product| %>
          <tr>
            <td><%= product.products_name %></td>
            <td><%= product.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No products found.</p>
  <% end %>
  </center>
</div>

app/views/products/show.html.erb
<h1>Product List</h1>

<% if @product.present? %>
  <table>
    <thead>
      <tr>
        <th>Product Name</th>
        <th>Price</th>
      </tr>
    </thead>
    <tbody>
      <tr>
        <td><%= @product.products_name %></td>
        <td><%= @product.price %></td>
      </tr>
    </tbody>
  </table>

  <h2>Ratings</h2>
  <table>
    <thead>
      <tr>
        <th>Rating Value</th>
        <th>Comment</th>
      </tr>
    </thead>
    <tbody>
      <% @product.ratings.each do |rating| %>
        <tr>
          <td><%= rating.rating_value %></td>
          <td><%= rating.comment %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% else %>
  <p>No products found.</p>
<% end %>

app/views/ratings/create.html.erb
<h1>Rating Created</h1>
<p>Rating information:</p>
<p>rating_value: <%= @rating.rating_value %></p>
<p>comment: <%= @rating.comment %></p>

app/views/ratings/new.html.erb
<%= form_for @rating do |f| %>

  <div class="field" style="margin-bottom: 8px;">
    <%= f.label :rating_value %>
    <%= f.text_field :rating_value %>
  </div>

  <div class="field" style="margin-bottom: 8px;">
    <%= f.label :comment %>
    <%= f.text_field :comment %>
  </div>

  <div class="field" style="margin-bottom: 8px;">
    <%= f.label :product_id %>
    <%= f.collection_select(:product_id, Product.all, :id, :products_name, include_blank: 'Select a Product') %>
  </div>

  <div class="field" style="margin-bottom: 8px;">
    <%= f.label :user_id %>
    <%= f.collection_select(:user_id, User.all, :id, :username, include_blank: 'Select a User') %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>

<% end %>

app/views/users/create.html.erb
<h1>User Created</h1>
<p>User information:</p>
<p>Username: <%= @user.username %></p>
<p>Email: <%= @user.email %></p>

app/views/users/index.html.erb
<h1>User List</h1>

<ul>
  <% @users.each do |user| %>
    <li><%= user.username %></li>
  <% end %>
</ul>

app/views/users/new.html.erb
<h1>New user</h1>

<%= form_with model: @user do |form| %>
  <div>
    <%= form.label :username %><br>
    <%= form.text_field :username %>
  </div>

  <div>
    <%= form.label :email %><br>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password %><br>
    <%= form.password_field :password %>
  </div>
  
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/new_import_file.html.erb
<%= form_with(url: '/users/import_users', method: 'post', local: false, multipart: true) do |form| %>
  <div class="form-group">
    <%= form.label 'file', 'Select a CSV file:' %>
    <%= form.file_field 'file' %>
  </div>
  
  <%= form.submit 'Import File', class: 'btn btn-primary' %>
<% end %>

app/views/welcomes/index.html.erb
<div class="container-fluid bg-primary">
  <div class="row">
    <div class="col-md-6 offset-md-3 text-center py-5">
      <p><i>Welcome to our application!</i></p>

      <%= link_to 'Sign Up', new_user_path, class: "btn btn-primary btn-lg mt-3" %>
      <%= link_to 'Login', authentication_index_path, class: "btn btn-secondary btn-lg mt-3" %>
    </div>
  </div>
</div>